/* eslint-disable sort-keys */

import { createFile } from '../utils';
import { prepareDriversData } from './utils';
import type { Driver } from './types';

const DRIVERS: Driver[] = [
  {
    id: 1,
    name: 'Arvid Lindblad',
    rarity: 'common',
    series: 1,
    stats: [
      { level: 1, overtaking: 5, defending: 6, qualifying: 2, raceStart: 3, tireManagement: 4 },
      { level: 2, overtaking: 9, defending: 10, qualifying: 5, raceStart: 5, tireManagement: 7 },
      { level: 3, overtaking: 12, defending: 13, qualifying: 7, raceStart: 7, tireManagement: 10 },
      { level: 4, overtaking: 15, defending: 17, qualifying: 10, raceStart: 9, tireManagement: 12 },
      { level: 5, overtaking: 18, defending: 20, qualifying: 12, raceStart: 11, tireManagement: 15 },
      { level: 6, overtaking: 21, defending: 24, qualifying: 14, raceStart: 12, tireManagement: 18 },
      { level: 7, overtaking: 24, defending: 27, qualifying: 17, raceStart: 14, tireManagement: 20 },
      { level: 8, overtaking: 27, defending: 31, qualifying: 19, raceStart: 16, tireManagement: 23 },
      { level: 9, overtaking: 30, defending: 34, qualifying: 21, raceStart: 18, tireManagement: 26 },
      { level: 10, overtaking: 33, defending: 38, qualifying: 24, raceStart: 19, tireManagement: 28 },
      { level: 11, overtaking: 36, defending: 41, qualifying: 26, raceStart: 21, tireManagement: 31 },
    ],
  },
  {
    id: 2,
    name: 'Franco Colapinto',
    rarity: 'common',
    series: 1,
    stats: [
      { level: 1, overtaking: 3, defending: 5, qualifying: 4, raceStart: 6, tireManagement: 2 },
      { level: 2, overtaking: 6, defending: 9, qualifying: 7, raceStart: 10, tireManagement: 4 },
      { level: 3, overtaking: 8, defending: 12, qualifying: 10, raceStart: 13, tireManagement: 6 },
      { level: 4, overtaking: 10, defending: 15, qualifying: 12, raceStart: 17, tireManagement: 8 },
      { level: 5, overtaking: 13, defending: 18, qualifying: 15, raceStart: 20, tireManagement: 10 },
      { level: 6, overtaking: 15, defending: 21, qualifying: 18, raceStart: 24, tireManagement: 12 },
      { level: 7, overtaking: 17, defending: 24, qualifying: 20, raceStart: 27, tireManagement: 14 },
      { level: 8, overtaking: 19, defending: 27, qualifying: 23, raceStart: 31, tireManagement: 16 },
      { level: 9, overtaking: 22, defending: 30, qualifying: 26, raceStart: 34, tireManagement: 17 },
      { level: 10, overtaking: 24, defending: 33, qualifying: 28, raceStart: 38, tireManagement: 19 },
      { level: 11, overtaking: 26, defending: 36, qualifying: 31, raceStart: 41, tireManagement: 21 },
    ],
  },
  {
    id: 3,
    name: 'Valtteri Bottas',
    rarity: 'common',
    series: 1,
    stats: [
      { level: 1, overtaking: 2, defending: 3, qualifying: 5, raceStart: 4, tireManagement: 6 },
      { level: 2, overtaking: 4, defending: 6, qualifying: 9, raceStart: 7, tireManagement: 10 },
      { level: 3, overtaking: 6, defending: 8, qualifying: 12, raceStart: 10, tireManagement: 13 },
      { level: 4, overtaking: 8, defending: 10, qualifying: 15, raceStart: 12, tireManagement: 17 },
      { level: 5, overtaking: 10, defending: 13, qualifying: 18, raceStart: 15, tireManagement: 20 },
      { level: 6, overtaking: 12, defending: 15, qualifying: 21, raceStart: 18, tireManagement: 24 },
      { level: 7, overtaking: 14, defending: 17, qualifying: 24, raceStart: 20, tireManagement: 27 },
      { level: 8, overtaking: 16, defending: 19, qualifying: 27, raceStart: 23, tireManagement: 31 },
      { level: 9, overtaking: 17, defending: 22, qualifying: 30, raceStart: 26, tireManagement: 34 },
      { level: 10, overtaking: 19, defending: 24, qualifying: 33, raceStart: 28, tireManagement: 38 },
      { level: 11, overtaking: 21, defending: 26, qualifying: 36, raceStart: 31, tireManagement: 41 },
    ],
  },
  {
    id: 4,
    name: 'Gabriel Bortoleto',
    rarity: 'rare',
    series: 1,
    stats: [
      { level: 1, overtaking: 19, defending: 3, qualifying: 11, raceStart: 15, tireManagement: 7 },
      { level: 2, overtaking: 22, defending: 6, qualifying: 14, raceStart: 18, tireManagement: 10 },
      { level: 3, overtaking: 26, defending: 9, qualifying: 17, raceStart: 22, tireManagement: 13 },
      { level: 4, overtaking: 29, defending: 12, qualifying: 21, raceStart: 25, tireManagement: 16 },
      { level: 5, overtaking: 33, defending: 15, qualifying: 24, raceStart: 29, tireManagement: 20 },
      { level: 6, overtaking: 37, defending: 18, qualifying: 27, raceStart: 32, tireManagement: 23 },
      { level: 7, overtaking: 40, defending: 21, qualifying: 31, raceStart: 35, tireManagement: 26 },
      { level: 8, overtaking: 44, defending: 24, qualifying: 34, raceStart: 39, tireManagement: 29 },
      { level: 9, overtaking: 47, defending: 27, qualifying: 37, raceStart: 42, tireManagement: 32 },
    ],
  },
  {
    id: 5,
    name: 'Pierre Gasly',
    rarity: 'epic',
    series: 1,
    stats: [
      { level: 1, overtaking: 9, defending: 13, qualifying: 21, raceStart: 5, tireManagement: 17 },
      { level: 2, overtaking: 13, defending: 17, qualifying: 25, raceStart: 9, tireManagement: 21 },
      { level: 3, overtaking: 17, defending: 21, qualifying: 30, raceStart: 12, tireManagement: 25 },
      { level: 4, overtaking: 20, defending: 25, qualifying: 34, raceStart: 16, tireManagement: 29 },
      { level: 5, overtaking: 24, defending: 29, qualifying: 38, raceStart: 19, tireManagement: 33 },
      { level: 6, overtaking: 28, defending: 32, qualifying: 42, raceStart: 23, tireManagement: 37 },
      { level: 7, overtaking: 31, defending: 36, qualifying: 46, raceStart: 27, tireManagement: 41 },
      { level: 8, overtaking: 35, defending: 40, qualifying: 50, raceStart: 30, tireManagement: 45 },
    ],
  },
  {
    id: 6,
    name: 'Gabriel Bortoleto',
    rarity: 'common',
    series: 2,
    stats: [
      { level: 1, overtaking: 17, defending: 1, qualifying: 9, raceStart: 13, tireManagement: 5 },
      { level: 2, overtaking: 20, defending: 3, qualifying: 12, raceStart: 16, tireManagement: 7 },
      { level: 3, overtaking: 23, defending: 6, qualifying: 14, raceStart: 18, tireManagement: 10 },
      { level: 4, overtaking: 26, defending: 8, qualifying: 17, raceStart: 21, tireManagement: 13 },
      { level: 5, overtaking: 28, defending: 11, qualifying: 20, raceStart: 24, tireManagement: 15 },
      { level: 6, overtaking: 31, defending: 13, qualifying: 22, raceStart: 27, tireManagement: 18 },
      { level: 7, overtaking: 34, defending: 16, qualifying: 25, raceStart: 30, tireManagement: 20 },
      { level: 8, overtaking: 37, defending: 18, qualifying: 28, raceStart: 32, tireManagement: 23 },
      { level: 9, overtaking: 40, defending: 21, qualifying: 30, raceStart: 35, tireManagement: 25 },
      { level: 10, overtaking: 43, defending: 23, qualifying: 33, raceStart: 38, tireManagement: 28 },
      { level: 11, overtaking: 46, defending: 26, qualifying: 36, raceStart: 41, tireManagement: 31 },
    ],
  },
  {
    id: 7,
    name: 'Pierre Gasly',
    rarity: 'common',
    series: 2,
    stats: [
      { level: 1, overtaking: 5, defending: 9, qualifying: 17, raceStart: 1, tireManagement: 13 },
      { level: 2, overtaking: 7, defending: 12, qualifying: 20, raceStart: 3, tireManagement: 16 },
      { level: 3, overtaking: 10, defending: 14, qualifying: 23, raceStart: 6, tireManagement: 18 },
      { level: 4, overtaking: 13, defending: 17, qualifying: 26, raceStart: 8, tireManagement: 21 },
      { level: 5, overtaking: 15, defending: 20, qualifying: 28, raceStart: 11, tireManagement: 24 },
      { level: 6, overtaking: 18, defending: 22, qualifying: 31, raceStart: 13, tireManagement: 27 },
      { level: 7, overtaking: 20, defending: 25, qualifying: 34, raceStart: 16, tireManagement: 30 },
      { level: 8, overtaking: 23, defending: 28, qualifying: 37, raceStart: 18, tireManagement: 32 },
      { level: 9, overtaking: 25, defending: 30, qualifying: 40, raceStart: 21, tireManagement: 35 },
      { level: 10, overtaking: 28, defending: 33, qualifying: 43, raceStart: 23, tireManagement: 38 },
      { level: 11, overtaking: 31, defending: 36, qualifying: 46, raceStart: 26, tireManagement: 41 },
    ],
  },
  {
    id: 8,
    name: 'Lance Stroll',
    rarity: 'common',
    series: 2,
    stats: [
      { level: 1, overtaking: 13, defending: 17, qualifying: 5, raceStart: 1, tireManagement: 9 },
      { level: 2, overtaking: 16, defending: 20, qualifying: 7, raceStart: 3, tireManagement: 12 },
      { level: 3, overtaking: 18, defending: 23, qualifying: 10, raceStart: 6, tireManagement: 14 },
      { level: 4, overtaking: 21, defending: 26, qualifying: 13, raceStart: 8, tireManagement: 17 },
      { level: 5, overtaking: 24, defending: 28, qualifying: 15, raceStart: 11, tireManagement: 20 },
      { level: 6, overtaking: 27, defending: 31, qualifying: 18, raceStart: 13, tireManagement: 22 },
      { level: 7, overtaking: 30, defending: 34, qualifying: 20, raceStart: 16, tireManagement: 25 },
      { level: 8, overtaking: 32, defending: 37, qualifying: 23, raceStart: 18, tireManagement: 28 },
      { level: 9, overtaking: 35, defending: 40, qualifying: 25, raceStart: 21, tireManagement: 30 },
      { level: 10, overtaking: 38, defending: 43, qualifying: 28, raceStart: 23, tireManagement: 33 },
      { level: 11, overtaking: 41, defending: 46, qualifying: 31, raceStart: 26, tireManagement: 36 },
    ],
  },
  {
    id: 9,
    name: 'Esteban Ocon',
    rarity: 'common',
    series: 2,
    stats: [
      { level: 1, overtaking: 9, defending: 5, qualifying: 1, raceStart: 13, tireManagement: 17 },
      { level: 2, overtaking: 12, defending: 7, qualifying: 3, raceStart: 16, tireManagement: 20 },
      { level: 3, overtaking: 14, defending: 10, qualifying: 6, raceStart: 18, tireManagement: 23 },
      { level: 4, overtaking: 17, defending: 13, qualifying: 8, raceStart: 21, tireManagement: 26 },
      { level: 5, overtaking: 20, defending: 15, qualifying: 11, raceStart: 24, tireManagement: 28 },
      { level: 6, overtaking: 22, defending: 18, qualifying: 13, raceStart: 27, tireManagement: 31 },
      { level: 7, overtaking: 25, defending: 20, qualifying: 16, raceStart: 30, tireManagement: 34 },
      { level: 8, overtaking: 28, defending: 23, qualifying: 18, raceStart: 32, tireManagement: 37 },
      { level: 9, overtaking: 30, defending: 25, qualifying: 21, raceStart: 35, tireManagement: 40 },
      { level: 10, overtaking: 33, defending: 28, qualifying: 23, raceStart: 38, tireManagement: 43 },
      { level: 11, overtaking: 36, defending: 31, qualifying: 26, raceStart: 41, tireManagement: 46 },
    ],
  },
  {
    id: 10,
    name: 'Valtteri Bottas',
    rarity: 'rare',
    series: 2,
    stats: [
      { level: 1, overtaking: 11, defending: 12, qualifying: 14, raceStart: 13, tireManagement: 15 },
      { level: 2, overtaking: 14, defending: 15, qualifying: 18, raceStart: 17, tireManagement: 20 },
      { level: 3, overtaking: 16, defending: 18, qualifying: 22, raceStart: 20, tireManagement: 24 },
      { level: 4, overtaking: 18, defending: 21, qualifying: 26, raceStart: 23, tireManagement: 28 },
      { level: 5, overtaking: 21, defending: 24, qualifying: 30, raceStart: 27, tireManagement: 33 },
      { level: 6, overtaking: 23, defending: 27, qualifying: 34, raceStart: 30, tireManagement: 37 },
      { level: 7, overtaking: 25, defending: 29, qualifying: 37, raceStart: 33, tireManagement: 41 },
      { level: 8, overtaking: 28, defending: 32, qualifying: 41, raceStart: 37, tireManagement: 46 },
      { level: 9, overtaking: 30, defending: 35, qualifying: 45, raceStart: 40, tireManagement: 50 },
    ],
  },
  {
    id: 11,
    name: 'Liam Lawson',
    rarity: 'common',
    series: 3,
    stats: [
      { level: 1, overtaking: 23, defending: 3, qualifying: 13, raceStart: 8, tireManagement: 18 },
      { level: 2, overtaking: 26, defending: 6, qualifying: 16, raceStart: 11, tireManagement: 21 },
      { level: 3, overtaking: 29, defending: 9, qualifying: 19, raceStart: 14, tireManagement: 24 },
      { level: 4, overtaking: 31, defending: 11, qualifying: 21, raceStart: 16, tireManagement: 26 },
      { level: 5, overtaking: 34, defending: 14, qualifying: 24, raceStart: 19, tireManagement: 29 },
      { level: 6, overtaking: 37, defending: 17, qualifying: 27, raceStart: 22, tireManagement: 32 },
      { level: 7, overtaking: 39, defending: 19, qualifying: 29, raceStart: 24, tireManagement: 34 },
      { level: 8, overtaking: 42, defending: 22, qualifying: 32, raceStart: 27, tireManagement: 37 },
      { level: 9, overtaking: 45, defending: 25, qualifying: 35, raceStart: 30, tireManagement: 40 },
      { level: 10, overtaking: 47, defending: 27, qualifying: 37, raceStart: 32, tireManagement: 42 },
      { level: 11, overtaking: 50, defending: 30, qualifying: 40, raceStart: 35, tireManagement: 45 },
    ],
  },
  {
    id: 12,
    name: 'Oliver Bearman',
    rarity: 'common',
    series: 3,
    stats: [
      { level: 1, overtaking: 8, defending: 13, qualifying: 18, raceStart: 23, tireManagement: 3 },
      { level: 2, overtaking: 11, defending: 16, qualifying: 21, raceStart: 26, tireManagement: 6 },
      { level: 3, overtaking: 14, defending: 19, qualifying: 24, raceStart: 29, tireManagement: 9 },
      { level: 4, overtaking: 16, defending: 21, qualifying: 26, raceStart: 31, tireManagement: 11 },
      { level: 5, overtaking: 19, defending: 24, qualifying: 29, raceStart: 34, tireManagement: 14 },
      { level: 6, overtaking: 22, defending: 27, qualifying: 32, raceStart: 37, tireManagement: 17 },
      { level: 7, overtaking: 24, defending: 29, qualifying: 34, raceStart: 39, tireManagement: 19 },
      { level: 8, overtaking: 27, defending: 32, qualifying: 37, raceStart: 42, tireManagement: 22 },
      { level: 9, overtaking: 30, defending: 35, qualifying: 40, raceStart: 45, tireManagement: 25 },
      { level: 10, overtaking: 32, defending: 37, qualifying: 42, raceStart: 47, tireManagement: 27 },
      { level: 11, overtaking: 35, defending: 40, qualifying: 45, raceStart: 50, tireManagement: 30 },
    ],
  },
  {
    id: 13,
    name: 'Isack Hadjar',
    rarity: 'common',
    series: 3,
    stats: [
      { level: 1, overtaking: 18, defending: 23, qualifying: 3, raceStart: 13, tireManagement: 8 },
      { level: 2, overtaking: 21, defending: 26, qualifying: 6, raceStart: 16, tireManagement: 11 },
      { level: 3, overtaking: 24, defending: 29, qualifying: 9, raceStart: 19, tireManagement: 14 },
      { level: 4, overtaking: 26, defending: 31, qualifying: 11, raceStart: 21, tireManagement: 16 },
      { level: 5, overtaking: 29, defending: 34, qualifying: 14, raceStart: 24, tireManagement: 19 },
      { level: 6, overtaking: 32, defending: 37, qualifying: 17, raceStart: 27, tireManagement: 22 },
      { level: 7, overtaking: 34, defending: 39, qualifying: 19, raceStart: 29, tireManagement: 24 },
      { level: 8, overtaking: 37, defending: 42, qualifying: 22, raceStart: 32, tireManagement: 27 },
      { level: 9, overtaking: 40, defending: 45, qualifying: 25, raceStart: 35, tireManagement: 30 },
      { level: 10, overtaking: 42, defending: 47, qualifying: 27, raceStart: 37, tireManagement: 32 },
      { level: 11, overtaking: 45, defending: 50, qualifying: 30, raceStart: 40, tireManagement: 35 },
    ],
  },
  {
    id: 14,
    name: 'Nico Hülkenberg',
    rarity: 'common',
    series: 3,
    stats: [
      { level: 1, overtaking: 13, defending: 18, qualifying: 23, raceStart: 8, tireManagement: 3 },
      { level: 2, overtaking: 16, defending: 21, qualifying: 26, raceStart: 11, tireManagement: 6 },
      { level: 3, overtaking: 19, defending: 24, qualifying: 29, raceStart: 14, tireManagement: 9 },
      { level: 4, overtaking: 21, defending: 26, qualifying: 31, raceStart: 16, tireManagement: 11 },
      { level: 5, overtaking: 24, defending: 29, qualifying: 34, raceStart: 19, tireManagement: 14 },
      { level: 6, overtaking: 27, defending: 32, qualifying: 37, raceStart: 22, tireManagement: 17 },
      { level: 7, overtaking: 29, defending: 34, qualifying: 39, raceStart: 24, tireManagement: 19 },
      { level: 8, overtaking: 32, defending: 37, qualifying: 42, raceStart: 27, tireManagement: 22 },
      { level: 9, overtaking: 35, defending: 40, qualifying: 45, raceStart: 30, tireManagement: 25 },
      { level: 10, overtaking: 37, defending: 42, qualifying: 47, raceStart: 32, tireManagement: 27 },
      { level: 11, overtaking: 40, defending: 45, qualifying: 50, raceStart: 35, tireManagement: 30 },
    ],
  },
  {
    id: 15,
    name: 'Arvid Lindblad',
    rarity: 'epic',
    series: 3,
    stats: [
      { level: 1, overtaking: 23, defending: 24, qualifying: 20, raceStart: 21, tireManagement: 22 },
      { level: 2, overtaking: 28, defending: 29, qualifying: 24, raceStart: 24, tireManagement: 26 },
      { level: 3, overtaking: 32, defending: 34, qualifying: 27, raceStart: 26, tireManagement: 30 },
      { level: 4, overtaking: 36, defending: 39, qualifying: 30, raceStart: 29, tireManagement: 34 },
      { level: 5, overtaking: 41, defending: 44, qualifying: 34, raceStart: 31, tireManagement: 38 },
      { level: 6, overtaking: 45, defending: 49, qualifying: 37, raceStart: 34, tireManagement: 41 },
      { level: 7, overtaking: 50, defending: 54, qualifying: 41, raceStart: 36, tireManagement: 45 },
      { level: 8, overtaking: 54, defending: 59, qualifying: 44, raceStart: 39, tireManagement: 49 },
    ],
  },
  {
    id: 16,
    name: 'Fernando Alonso',
    rarity: 'common',
    series: 4,
    stats: [
      { level: 1, overtaking: 28, defending: 13, qualifying: 8, raceStart: 23, tireManagement: 18 },
      { level: 2, overtaking: 30, defending: 15, qualifying: 10, raceStart: 25, tireManagement: 20 },
      { level: 3, overtaking: 33, defending: 18, qualifying: 13, raceStart: 28, tireManagement: 23 },
      { level: 4, overtaking: 36, defending: 21, qualifying: 16, raceStart: 31, tireManagement: 26 },
      { level: 5, overtaking: 38, defending: 23, qualifying: 18, raceStart: 33, tireManagement: 28 },
      { level: 6, overtaking: 41, defending: 26, qualifying: 21, raceStart: 36, tireManagement: 31 },
      { level: 7, overtaking: 44, defending: 29, qualifying: 24, raceStart: 39, tireManagement: 34 },
      { level: 8, overtaking: 46, defending: 31, qualifying: 26, raceStart: 41, tireManagement: 36 },
      { level: 9, overtaking: 49, defending: 34, qualifying: 29, raceStart: 44, tireManagement: 39 },
      { level: 10, overtaking: 52, defending: 37, qualifying: 32, raceStart: 47, tireManagement: 42 },
      { level: 11, overtaking: 55, defending: 40, qualifying: 35, raceStart: 50, tireManagement: 45 },
    ],
  },
  {
    id: 17,
    name: 'Carlos Sainz',
    rarity: 'common',
    series: 4,
    stats: [
      { level: 1, overtaking: 13, defending: 23, qualifying: 18, raceStart: 8, tireManagement: 28 },
      { level: 2, overtaking: 15, defending: 25, qualifying: 20, raceStart: 10, tireManagement: 30 },
      { level: 3, overtaking: 18, defending: 28, qualifying: 23, raceStart: 13, tireManagement: 33 },
      { level: 4, overtaking: 21, defending: 31, qualifying: 26, raceStart: 16, tireManagement: 36 },
      { level: 5, overtaking: 23, defending: 33, qualifying: 28, raceStart: 18, tireManagement: 38 },
      { level: 6, overtaking: 26, defending: 36, qualifying: 31, raceStart: 21, tireManagement: 41 },
      { level: 7, overtaking: 29, defending: 39, qualifying: 34, raceStart: 24, tireManagement: 44 },
      { level: 8, overtaking: 31, defending: 41, qualifying: 36, raceStart: 26, tireManagement: 46 },
      { level: 9, overtaking: 34, defending: 44, qualifying: 39, raceStart: 29, tireManagement: 49 },
      { level: 10, overtaking: 37, defending: 47, qualifying: 42, raceStart: 32, tireManagement: 52 },
      { level: 11, overtaking: 40, defending: 50, qualifying: 45, raceStart: 35, tireManagement: 55 },
    ],
  },
  {
    id: 18,
    name: 'Alex Albon',
    rarity: 'common',
    series: 4,
    stats: [
      { level: 1, overtaking: 8, defending: 28, qualifying: 23, raceStart: 13, tireManagement: 18 },
      { level: 2, overtaking: 11, defending: 30, qualifying: 25, raceStart: 16, tireManagement: 19 },
      { level: 3, overtaking: 14, defending: 33, qualifying: 27, raceStart: 20, tireManagement: 21 },
      { level: 4, overtaking: 17, defending: 36, qualifying: 29, raceStart: 24, tireManagement: 23 },
      { level: 5, overtaking: 20, defending: 38, qualifying: 31, raceStart: 27, tireManagement: 24 },
      { level: 6, overtaking: 24, defending: 41, qualifying: 34, raceStart: 31, tireManagement: 26 },
      { level: 7, overtaking: 27, defending: 44, qualifying: 36, raceStart: 35, tireManagement: 28 },
      { level: 8, overtaking: 30, defending: 46, qualifying: 38, raceStart: 38, tireManagement: 29 },
      { level: 9, overtaking: 33, defending: 49, qualifying: 40, raceStart: 42, tireManagement: 31 },
      { level: 10, overtaking: 36, defending: 52, qualifying: 42, raceStart: 46, tireManagement: 33 },
      { level: 11, overtaking: 40, defending: 55, qualifying: 45, raceStart: 50, tireManagement: 35 },
    ],
  },
  {
    id: 19,
    name: 'Andrea Kimi Antonelli',
    rarity: 'common',
    series: 4,
    stats: [
      { level: 1, overtaking: 18, defending: 8, qualifying: 28, raceStart: 23, tireManagement: 13 },
      { level: 2, overtaking: 20, defending: 10, qualifying: 30, raceStart: 25, tireManagement: 15 },
      { level: 3, overtaking: 23, defending: 13, qualifying: 33, raceStart: 28, tireManagement: 18 },
      { level: 4, overtaking: 26, defending: 16, qualifying: 36, raceStart: 31, tireManagement: 21 },
      { level: 5, overtaking: 28, defending: 18, qualifying: 38, raceStart: 33, tireManagement: 23 },
      { level: 6, overtaking: 31, defending: 21, qualifying: 41, raceStart: 36, tireManagement: 26 },
      { level: 7, overtaking: 34, defending: 24, qualifying: 44, raceStart: 39, tireManagement: 29 },
      { level: 8, overtaking: 36, defending: 26, qualifying: 46, raceStart: 41, tireManagement: 31 },
      { level: 9, overtaking: 39, defending: 29, qualifying: 49, raceStart: 44, tireManagement: 34 },
      { level: 10, overtaking: 42, defending: 32, qualifying: 52, raceStart: 47, tireManagement: 37 },
      { level: 11, overtaking: 45, defending: 35, qualifying: 55, raceStart: 50, tireManagement: 40 },
    ],
  },
  {
    id: 20,
    name: 'Sergio Perez',
    rarity: 'common',
    series: 4,
    stats: [
      { level: 1, overtaking: 8, defending: 18, qualifying: 13, raceStart: 28, tireManagement: 23 },
      { level: 2, overtaking: 10, defending: 20, qualifying: 15, raceStart: 30, tireManagement: 25 },
      { level: 3, overtaking: 13, defending: 23, qualifying: 18, raceStart: 33, tireManagement: 28 },
      { level: 4, overtaking: 16, defending: 26, qualifying: 21, raceStart: 36, tireManagement: 31 },
      { level: 5, overtaking: 18, defending: 28, qualifying: 23, raceStart: 38, tireManagement: 33 },
      { level: 6, overtaking: 21, defending: 31, qualifying: 26, raceStart: 41, tireManagement: 36 },
      { level: 7, overtaking: 24, defending: 34, qualifying: 29, raceStart: 44, tireManagement: 39 },
      { level: 8, overtaking: 26, defending: 36, qualifying: 31, raceStart: 46, tireManagement: 41 },
      { level: 9, overtaking: 29, defending: 39, qualifying: 34, raceStart: 49, tireManagement: 44 },
      { level: 10, overtaking: 32, defending: 42, qualifying: 37, raceStart: 52, tireManagement: 47 },
      { level: 11, overtaking: 35, defending: 45, qualifying: 40, raceStart: 55, tireManagement: 50 },
    ],
  },
  {
    id: 21,
    name: 'Valtteri Bottas',
    rarity: 'epic',
    series: 4,
    stats: [
      { level: 1, overtaking: 25, defending: 26, qualifying: 28, raceStart: 27, tireManagement: 29 },
      { level: 2, overtaking: 27, defending: 29, qualifying: 32, raceStart: 31, tireManagement: 34 },
      { level: 3, overtaking: 30, defending: 32, qualifying: 36, raceStart: 34, tireManagement: 39 },
      { level: 4, overtaking: 33, defending: 35, qualifying: 41, raceStart: 38, tireManagement: 44 },
      { level: 5, overtaking: 35, defending: 39, qualifying: 45, raceStart: 42, tireManagement: 49 },
      { level: 6, overtaking: 38, defending: 42, qualifying: 50, raceStart: 46, tireManagement: 53 },
      { level: 7, overtaking: 41, defending: 45, qualifying: 54, raceStart: 50, tireManagement: 58 },
      { level: 8, overtaking: 43, defending: 48, qualifying: 58, raceStart: 53, tireManagement: 63 },
    ],
  },
  {
    id: 22,
    name: 'Lewis Hamilton',
    rarity: 'common',
    series: 5,
    stats: [
      { level: 1, overtaking: 27, defending: 17, qualifying: 22, raceStart: 12, tireManagement: 32 },
      { level: 2, overtaking: 30, defending: 20, qualifying: 25, raceStart: 15, tireManagement: 35 },
      { level: 3, overtaking: 33, defending: 23, qualifying: 28, raceStart: 18, tireManagement: 38 },
      { level: 4, overtaking: 35, defending: 25, qualifying: 30, raceStart: 20, tireManagement: 40 },
      { level: 5, overtaking: 38, defending: 28, qualifying: 33, raceStart: 23, tireManagement: 43 },
      { level: 6, overtaking: 41, defending: 31, qualifying: 36, raceStart: 26, tireManagement: 46 },
      { level: 7, overtaking: 43, defending: 33, qualifying: 38, raceStart: 28, tireManagement: 48 },
      { level: 8, overtaking: 46, defending: 36, qualifying: 41, raceStart: 31, tireManagement: 51 },
      { level: 9, overtaking: 49, defending: 39, qualifying: 44, raceStart: 34, tireManagement: 54 },
      { level: 10, overtaking: 51, defending: 41, qualifying: 46, raceStart: 36, tireManagement: 56 },
      { level: 11, overtaking: 54, defending: 44, qualifying: 49, raceStart: 39, tireManagement: 59 },
    ],
  },
  {
    id: 23,
    name: 'Charles Leclerc',
    rarity: 'common',
    series: 5,
    stats: [
      { level: 1, overtaking: 12, defending: 22, qualifying: 27, raceStart: 32, tireManagement: 17 },
      { level: 2, overtaking: 15, defending: 25, qualifying: 30, raceStart: 35, tireManagement: 20 },
      { level: 3, overtaking: 18, defending: 28, qualifying: 33, raceStart: 38, tireManagement: 23 },
      { level: 4, overtaking: 20, defending: 30, qualifying: 35, raceStart: 40, tireManagement: 25 },
      { level: 5, overtaking: 23, defending: 33, qualifying: 38, raceStart: 43, tireManagement: 28 },
      { level: 6, overtaking: 26, defending: 36, qualifying: 41, raceStart: 46, tireManagement: 31 },
      { level: 7, overtaking: 28, defending: 38, qualifying: 43, raceStart: 48, tireManagement: 33 },
      { level: 8, overtaking: 31, defending: 41, qualifying: 46, raceStart: 51, tireManagement: 36 },
      { level: 9, overtaking: 34, defending: 44, qualifying: 49, raceStart: 54, tireManagement: 39 },
      { level: 10, overtaking: 36, defending: 46, qualifying: 51, raceStart: 56, tireManagement: 41 },
      { level: 11, overtaking: 39, defending: 49, qualifying: 54, raceStart: 59, tireManagement: 44 },
    ],
  },
  {
    id: 24,
    name: 'George Russell',
    rarity: 'common',
    series: 5,
    stats: [
      { level: 1, overtaking: 32, defending: 12, qualifying: 17, raceStart: 22, tireManagement: 27 },
      { level: 2, overtaking: 35, defending: 15, qualifying: 20, raceStart: 25, tireManagement: 30 },
      { level: 3, overtaking: 38, defending: 18, qualifying: 23, raceStart: 28, tireManagement: 33 },
      { level: 4, overtaking: 40, defending: 20, qualifying: 25, raceStart: 30, tireManagement: 35 },
      { level: 5, overtaking: 43, defending: 23, qualifying: 28, raceStart: 33, tireManagement: 38 },
      { level: 6, overtaking: 46, defending: 26, qualifying: 31, raceStart: 36, tireManagement: 41 },
      { level: 7, overtaking: 48, defending: 28, qualifying: 33, raceStart: 38, tireManagement: 43 },
      { level: 8, overtaking: 51, defending: 31, qualifying: 36, raceStart: 41, tireManagement: 46 },
      { level: 9, overtaking: 54, defending: 34, qualifying: 39, raceStart: 44, tireManagement: 49 },
      { level: 10, overtaking: 56, defending: 36, qualifying: 41, raceStart: 46, tireManagement: 51 },
      { level: 11, overtaking: 59, defending: 39, qualifying: 44, raceStart: 49, tireManagement: 54 },
    ],
  },
  {
    id: 25,
    name: 'Oscar Piastri',
    rarity: 'common',
    series: 5,
    stats: [
      { level: 1, overtaking: 22, defending: 32, qualifying: 12, raceStart: 27, tireManagement: 17 },
      { level: 2, overtaking: 25, defending: 35, qualifying: 15, raceStart: 30, tireManagement: 20 },
      { level: 3, overtaking: 28, defending: 38, qualifying: 18, raceStart: 33, tireManagement: 23 },
      { level: 4, overtaking: 30, defending: 40, qualifying: 20, raceStart: 35, tireManagement: 25 },
      { level: 5, overtaking: 33, defending: 43, qualifying: 23, raceStart: 38, tireManagement: 28 },
      { level: 6, overtaking: 36, defending: 46, qualifying: 26, raceStart: 41, tireManagement: 31 },
      { level: 7, overtaking: 38, defending: 48, qualifying: 28, raceStart: 43, tireManagement: 33 },
      { level: 8, overtaking: 41, defending: 51, qualifying: 31, raceStart: 46, tireManagement: 36 },
      { level: 9, overtaking: 44, defending: 54, qualifying: 34, raceStart: 49, tireManagement: 39 },
      { level: 10, overtaking: 46, defending: 56, qualifying: 36, raceStart: 51, tireManagement: 41 },
      { level: 11, overtaking: 49, defending: 59, qualifying: 39, raceStart: 54, tireManagement: 44 },
    ],
  },
  {
    id: 26,
    name: 'Max Verstappen',
    rarity: 'common',
    series: 5,
    stats: [
      { level: 1, overtaking: 27, defending: 17, qualifying: 32, raceStart: 12, tireManagement: 22 },
      { level: 2, overtaking: 30, defending: 20, qualifying: 35, raceStart: 15, tireManagement: 25 },
      { level: 3, overtaking: 33, defending: 23, qualifying: 38, raceStart: 18, tireManagement: 28 },
      { level: 4, overtaking: 35, defending: 25, qualifying: 40, raceStart: 20, tireManagement: 30 },
      { level: 5, overtaking: 38, defending: 28, qualifying: 43, raceStart: 23, tireManagement: 33 },
      { level: 6, overtaking: 41, defending: 31, qualifying: 46, raceStart: 26, tireManagement: 36 },
      { level: 7, overtaking: 43, defending: 33, qualifying: 48, raceStart: 28, tireManagement: 38 },
      { level: 8, overtaking: 46, defending: 36, qualifying: 51, raceStart: 31, tireManagement: 41 },
      { level: 9, overtaking: 49, defending: 39, qualifying: 54, raceStart: 34, tireManagement: 44 },
      { level: 10, overtaking: 51, defending: 41, qualifying: 56, raceStart: 36, tireManagement: 46 },
      { level: 11, overtaking: 54, defending: 44, qualifying: 59, raceStart: 39, tireManagement: 49 },
    ],
  },
  {
    id: 27,
    name: 'Franco Colapinto',
    rarity: 'rare',
    series: 5,
    stats: [
      { level: 1, overtaking: 24, defending: 26, qualifying: 25, raceStart: 27, tireManagement: 23 },
      { level: 2, overtaking: 27, defending: 30, qualifying: 28, raceStart: 31, tireManagement: 25 },
      { level: 3, overtaking: 30, defending: 34, qualifying: 32, raceStart: 36, tireManagement: 28 },
      { level: 4, overtaking: 32, defending: 37, qualifying: 35, raceStart: 40, tireManagement: 30 },
      { level: 5, overtaking: 35, defending: 41, qualifying: 38, raceStart: 44, tireManagement: 32 },
      { level: 6, overtaking: 38, defending: 45, qualifying: 42, raceStart: 49, tireManagement: 35 },
      { level: 7, overtaking: 41, defending: 49, qualifying: 45, raceStart: 53, tireManagement: 37 },
      { level: 8, overtaking: 44, defending: 53, qualifying: 48, raceStart: 57, tireManagement: 39 },
      { level: 9, overtaking: 47, defending: 57, qualifying: 52, raceStart: 62, tireManagement: 42 },
    ],
  },
  {
    id: 28,
    name: 'Lando Norris',
    rarity: 'common',
    series: 6,
    stats: [
      { level: 1, overtaking: 25, defending: 15, qualifying: 30, raceStart: 20, tireManagement: 35 },
      { level: 2, overtaking: 28, defending: 18, qualifying: 33, raceStart: 23, tireManagement: 38 },
      { level: 3, overtaking: 30, defending: 20, qualifying: 35, raceStart: 25, tireManagement: 40 },
      { level: 4, overtaking: 33, defending: 23, qualifying: 38, raceStart: 28, tireManagement: 43 },
      { level: 5, overtaking: 36, defending: 26, qualifying: 41, raceStart: 31, tireManagement: 46 },
      { level: 6, overtaking: 38, defending: 28, qualifying: 43, raceStart: 33, tireManagement: 48 },
      { level: 7, overtaking: 41, defending: 31, qualifying: 46, raceStart: 36, tireManagement: 51 },
      { level: 8, overtaking: 44, defending: 34, qualifying: 49, raceStart: 39, tireManagement: 54 },
      { level: 9, overtaking: 46, defending: 36, qualifying: 51, raceStart: 41, tireManagement: 56 },
      { level: 10, overtaking: 49, defending: 39, qualifying: 54, raceStart: 44, tireManagement: 59 },
      { level: 11, overtaking: 52, defending: 42, qualifying: 57, raceStart: 47, tireManagement: 62 },
    ],
  },
  {
    id: 29,
    name: 'Arvid Lindblad',
    rarity: 'rare',
    series: 6,
    stats: [
      { level: 1, overtaking: 28, defending: 29, qualifying: 25, raceStart: 26, tireManagement: 27 },
      { level: 2, overtaking: 32, defending: 33, qualifying: 28, raceStart: 28, tireManagement: 30 },
      { level: 3, overtaking: 35, defending: 37, qualifying: 31, raceStart: 30, tireManagement: 33 },
      { level: 4, overtaking: 39, defending: 42, qualifying: 34, raceStart: 32, tireManagement: 37 },
      { level: 5, overtaking: 43, defending: 46, qualifying: 37, raceStart: 35, tireManagement: 40 },
      { level: 6, overtaking: 47, defending: 50, qualifying: 40, raceStart: 37, tireManagement: 43 },
      { level: 7, overtaking: 51, defending: 55, qualifying: 42, raceStart: 39, tireManagement: 47 },
      { level: 8, overtaking: 55, defending: 59, qualifying: 45, raceStart: 41, tireManagement: 50 },
      { level: 9, overtaking: 58, defending: 63, qualifying: 48, raceStart: 43, tireManagement: 53 },
    ],
  },
  {
    id: 30,
    name: 'Pierre Gasly',
    rarity: 'rare',
    series: 6,
    stats: [
      { level: 1, overtaking: 23, defending: 27, qualifying: 35, raceStart: 19, tireManagement: 31 },
      { level: 2, overtaking: 26, defending: 30, qualifying: 38, raceStart: 22, tireManagement: 34 },
      { level: 3, overtaking: 29, defending: 33, qualifying: 42, raceStart: 25, tireManagement: 38 },
      { level: 4, overtaking: 32, defending: 37, qualifying: 45, raceStart: 28, tireManagement: 41 },
      { level: 5, overtaking: 36, defending: 40, qualifying: 49, raceStart: 31, tireManagement: 45 },
      { level: 6, overtaking: 39, defending: 43, qualifying: 53, raceStart: 34, tireManagement: 48 },
      { level: 7, overtaking: 42, defending: 47, qualifying: 56, raceStart: 37, tireManagement: 51 },
      { level: 8, overtaking: 45, defending: 50, qualifying: 60, raceStart: 40, tireManagement: 55 },
      { level: 9, overtaking: 48, defending: 53, qualifying: 63, raceStart: 43, tireManagement: 58 },
    ],
  },
  {
    id: 31,
    name: 'Lance Stroll',
    rarity: 'rare',
    series: 6,
    stats: [
      { level: 1, overtaking: 31, defending: 35, qualifying: 23, raceStart: 19, tireManagement: 27 },
      { level: 2, overtaking: 34, defending: 38, qualifying: 26, raceStart: 22, tireManagement: 30 },
      { level: 3, overtaking: 38, defending: 42, qualifying: 29, raceStart: 25, tireManagement: 33 },
      { level: 4, overtaking: 41, defending: 45, qualifying: 32, raceStart: 28, tireManagement: 37 },
      { level: 5, overtaking: 45, defending: 49, qualifying: 36, raceStart: 31, tireManagement: 40 },
      { level: 6, overtaking: 48, defending: 53, qualifying: 39, raceStart: 34, tireManagement: 43 },
      { level: 7, overtaking: 51, defending: 56, qualifying: 42, raceStart: 37, tireManagement: 47 },
      { level: 8, overtaking: 55, defending: 60, qualifying: 45, raceStart: 40, tireManagement: 50 },
      { level: 9, overtaking: 58, defending: 63, qualifying: 48, raceStart: 43, tireManagement: 53 },
    ],
  },
  {
    id: 32,
    name: 'Franco Colapinto',
    rarity: 'epic',
    series: 6,
    stats: [
      { level: 1, overtaking: 35, defending: 37, qualifying: 36, raceStart: 38, tireManagement: 34 },
      { level: 2, overtaking: 38, defending: 41, qualifying: 39, raceStart: 43, tireManagement: 36 },
      { level: 3, overtaking: 41, defending: 45, qualifying: 43, raceStart: 48, tireManagement: 39 },
      { level: 4, overtaking: 44, defending: 50, qualifying: 47, raceStart: 52, tireManagement: 42 },
      { level: 5, overtaking: 48, defending: 54, qualifying: 51, raceStart: 57, tireManagement: 44 },
      { level: 6, overtaking: 51, defending: 59, qualifying: 55, raceStart: 62, tireManagement: 47 },
      { level: 7, overtaking: 54, defending: 63, qualifying: 58, raceStart: 67, tireManagement: 50 },
      { level: 8, overtaking: 57, defending: 67, qualifying: 62, raceStart: 72, tireManagement: 52 },
    ],
  },
  {
    id: 33,
    name: 'Esteban Ocon',
    rarity: 'rare',
    series: 7,
    stats: [
      { level: 1, overtaking: 31, defending: 27, qualifying: 23, raceStart: 35, tireManagement: 39 },
      { level: 2, overtaking: 34, defending: 30, qualifying: 26, raceStart: 39, tireManagement: 43 },
      { level: 3, overtaking: 38, defending: 34, qualifying: 29, raceStart: 42, tireManagement: 46 },
      { level: 4, overtaking: 41, defending: 37, qualifying: 32, raceStart: 46, tireManagement: 50 },
      { level: 5, overtaking: 45, defending: 40, qualifying: 36, raceStart: 49, tireManagement: 54 },
      { level: 6, overtaking: 48, defending: 43, qualifying: 39, raceStart: 52, tireManagement: 57 },
      { level: 7, overtaking: 51, defending: 46, qualifying: 42, raceStart: 56, tireManagement: 61 },
      { level: 8, overtaking: 55, defending: 50, qualifying: 45, raceStart: 59, tireManagement: 64 },
      { level: 9, overtaking: 58, defending: 53, qualifying: 48, raceStart: 63, tireManagement: 68 },
    ],
  },
  {
    id: 34,
    name: 'Liam Lawson',
    rarity: 'rare',
    series: 7,
    stats: [
      { level: 1, overtaking: 41, defending: 21, qualifying: 31, raceStart: 26, tireManagement: 36 },
      { level: 2, overtaking: 44, defending: 24, qualifying: 34, raceStart: 29, tireManagement: 39 },
      { level: 3, overtaking: 48, defending: 28, qualifying: 38, raceStart: 33, tireManagement: 43 },
      { level: 4, overtaking: 51, defending: 31, qualifying: 41, raceStart: 36, tireManagement: 46 },
      { level: 5, overtaking: 55, defending: 35, qualifying: 45, raceStart: 40, tireManagement: 50 },
      { level: 6, overtaking: 58, defending: 38, qualifying: 48, raceStart: 43, tireManagement: 53 },
      { level: 7, overtaking: 61, defending: 41, qualifying: 51, raceStart: 46, tireManagement: 56 },
      { level: 8, overtaking: 65, defending: 45, qualifying: 55, raceStart: 50, tireManagement: 60 },
      { level: 9, overtaking: 68, defending: 48, qualifying: 58, raceStart: 53, tireManagement: 63 },
    ],
  },
  {
    id: 35,
    name: 'Oliver Bearman',
    rarity: 'rare',
    series: 7,
    stats: [
      { level: 1, overtaking: 26, defending: 31, qualifying: 36, raceStart: 41, tireManagement: 21 },
      { level: 2, overtaking: 29, defending: 34, qualifying: 39, raceStart: 44, tireManagement: 24 },
      { level: 3, overtaking: 33, defending: 38, qualifying: 43, raceStart: 48, tireManagement: 28 },
      { level: 4, overtaking: 36, defending: 41, qualifying: 46, raceStart: 51, tireManagement: 31 },
      { level: 5, overtaking: 40, defending: 45, qualifying: 50, raceStart: 55, tireManagement: 35 },
      { level: 6, overtaking: 43, defending: 48, qualifying: 53, raceStart: 58, tireManagement: 38 },
      { level: 7, overtaking: 46, defending: 51, qualifying: 56, raceStart: 61, tireManagement: 41 },
      { level: 8, overtaking: 50, defending: 55, qualifying: 60, raceStart: 65, tireManagement: 45 },
      { level: 9, overtaking: 53, defending: 58, qualifying: 63, raceStart: 68, tireManagement: 48 },
    ],
  },
  {
    id: 36,
    name: 'Isack Hadjar',
    rarity: 'rare',
    series: 7,
    stats: [
      { level: 1, overtaking: 36, defending: 41, qualifying: 21, raceStart: 31, tireManagement: 26 },
      { level: 2, overtaking: 39, defending: 44, qualifying: 24, raceStart: 34, tireManagement: 29 },
      { level: 3, overtaking: 43, defending: 48, qualifying: 28, raceStart: 38, tireManagement: 33 },
      { level: 4, overtaking: 46, defending: 51, qualifying: 31, raceStart: 41, tireManagement: 36 },
      { level: 5, overtaking: 50, defending: 55, qualifying: 35, raceStart: 45, tireManagement: 40 },
      { level: 6, overtaking: 53, defending: 58, qualifying: 38, raceStart: 48, tireManagement: 43 },
      { level: 7, overtaking: 56, defending: 61, qualifying: 41, raceStart: 51, tireManagement: 46 },
      { level: 8, overtaking: 60, defending: 65, qualifying: 45, raceStart: 55, tireManagement: 50 },
      { level: 9, overtaking: 63, defending: 68, qualifying: 48, raceStart: 58, tireManagement: 53 },
    ],
  },
  {
    id: 37,
    name: 'Nico Hülkenberg',
    rarity: 'rare',
    series: 7,
    stats: [
      { level: 1, overtaking: 31, defending: 36, qualifying: 41, raceStart: 26, tireManagement: 21 },
      { level: 2, overtaking: 34, defending: 39, qualifying: 44, raceStart: 29, tireManagement: 24 },
      { level: 3, overtaking: 38, defending: 43, qualifying: 48, raceStart: 33, tireManagement: 28 },
      { level: 4, overtaking: 41, defending: 46, qualifying: 51, raceStart: 36, tireManagement: 31 },
      { level: 5, overtaking: 45, defending: 50, qualifying: 55, raceStart: 40, tireManagement: 35 },
      { level: 6, overtaking: 48, defending: 53, qualifying: 58, raceStart: 43, tireManagement: 38 },
      { level: 7, overtaking: 51, defending: 56, qualifying: 61, raceStart: 46, tireManagement: 41 },
      { level: 8, overtaking: 55, defending: 60, qualifying: 65, raceStart: 50, tireManagement: 45 },
      { level: 9, overtaking: 58, defending: 63, qualifying: 68, raceStart: 53, tireManagement: 48 },
    ],
  },
  {
    id: 38,
    name: 'Fernando Alonso',
    rarity: 'rare',
    series: 8,
    stats: [
      { level: 1, overtaking: 46, defending: 31, qualifying: 26, raceStart: 41, tireManagement: 36 },
      { level: 2, overtaking: 49, defending: 34, qualifying: 29, raceStart: 44, tireManagement: 39 },
      { level: 3, overtaking: 52, defending: 37, qualifying: 32, raceStart: 47, tireManagement: 42 },
      { level: 4, overtaking: 56, defending: 41, qualifying: 36, raceStart: 51, tireManagement: 46 },
      { level: 5, overtaking: 59, defending: 44, qualifying: 39, raceStart: 54, tireManagement: 49 },
      { level: 6, overtaking: 62, defending: 47, qualifying: 42, raceStart: 57, tireManagement: 52 },
      { level: 7, overtaking: 66, defending: 51, qualifying: 46, raceStart: 61, tireManagement: 56 },
      { level: 8, overtaking: 69, defending: 54, qualifying: 49, raceStart: 64, tireManagement: 59 },
      { level: 9, overtaking: 72, defending: 57, qualifying: 52, raceStart: 67, tireManagement: 62 },
    ],
  },
  {
    id: 39,
    name: 'Carlos Sainz',
    rarity: 'rare',
    series: 8,
    stats: [
      { level: 1, overtaking: 31, defending: 41, qualifying: 36, raceStart: 26, tireManagement: 46 },
      { level: 2, overtaking: 34, defending: 44, qualifying: 39, raceStart: 29, tireManagement: 49 },
      { level: 3, overtaking: 37, defending: 47, qualifying: 42, raceStart: 32, tireManagement: 52 },
      { level: 4, overtaking: 41, defending: 51, qualifying: 46, raceStart: 36, tireManagement: 56 },
      { level: 5, overtaking: 44, defending: 54, qualifying: 49, raceStart: 39, tireManagement: 59 },
      { level: 6, overtaking: 47, defending: 57, qualifying: 52, raceStart: 42, tireManagement: 62 },
      { level: 7, overtaking: 51, defending: 61, qualifying: 56, raceStart: 46, tireManagement: 66 },
      { level: 8, overtaking: 54, defending: 64, qualifying: 59, raceStart: 49, tireManagement: 69 },
      { level: 9, overtaking: 57, defending: 67, qualifying: 62, raceStart: 52, tireManagement: 72 },
    ],
  },
  {
    id: 40,
    name: 'Alex Albon',
    rarity: 'rare',
    series: 8,
    stats: [
      { level: 1, overtaking: 26, defending: 46, qualifying: 41, raceStart: 31, tireManagement: 36 },
      { level: 2, overtaking: 30, defending: 49, qualifying: 43, raceStart: 35, tireManagement: 38 },
      { level: 3, overtaking: 34, defending: 52, qualifying: 46, raceStart: 40, tireManagement: 40 },
      { level: 4, overtaking: 37, defending: 56, qualifying: 49, raceStart: 44, tireManagement: 42 },
      { level: 5, overtaking: 41, defending: 59, qualifying: 51, raceStart: 49, tireManagement: 44 },
      { level: 6, overtaking: 45, defending: 62, qualifying: 54, raceStart: 54, tireManagement: 46 },
      { level: 7, overtaking: 49, defending: 66, qualifying: 57, raceStart: 58, tireManagement: 48 },
      { level: 8, overtaking: 53, defending: 69, qualifying: 60, raceStart: 63, tireManagement: 50 },
      { level: 9, overtaking: 57, defending: 72, qualifying: 62, raceStart: 67, tireManagement: 52 },
    ],
  },
  {
    id: 41,
    name: 'Andrea Kimi Antonelli',
    rarity: 'rare',
    series: 8,
    stats: [
      { level: 1, overtaking: 36, defending: 26, qualifying: 46, raceStart: 41, tireManagement: 31 },
      { level: 2, overtaking: 39, defending: 29, qualifying: 49, raceStart: 44, tireManagement: 34 },
      { level: 3, overtaking: 42, defending: 32, qualifying: 52, raceStart: 47, tireManagement: 37 },
      { level: 4, overtaking: 46, defending: 36, qualifying: 56, raceStart: 51, tireManagement: 41 },
      { level: 5, overtaking: 49, defending: 39, qualifying: 59, raceStart: 54, tireManagement: 44 },
      { level: 6, overtaking: 52, defending: 42, qualifying: 62, raceStart: 57, tireManagement: 47 },
      { level: 7, overtaking: 56, defending: 46, qualifying: 66, raceStart: 61, tireManagement: 51 },
      { level: 8, overtaking: 59, defending: 49, qualifying: 69, raceStart: 64, tireManagement: 54 },
      { level: 9, overtaking: 62, defending: 52, qualifying: 72, raceStart: 67, tireManagement: 57 },
    ],
  },
  {
    id: 42,
    name: 'Sergio Perez',
    rarity: 'rare',
    series: 8,
    stats: [
      { level: 1, overtaking: 26, defending: 36, qualifying: 31, raceStart: 46, tireManagement: 41 },
      { level: 2, overtaking: 29, defending: 39, qualifying: 34, raceStart: 49, tireManagement: 44 },
      { level: 3, overtaking: 32, defending: 42, qualifying: 37, raceStart: 52, tireManagement: 47 },
      { level: 4, overtaking: 36, defending: 46, qualifying: 41, raceStart: 56, tireManagement: 51 },
      { level: 5, overtaking: 39, defending: 49, qualifying: 44, raceStart: 59, tireManagement: 54 },
      { level: 6, overtaking: 42, defending: 52, qualifying: 47, raceStart: 62, tireManagement: 57 },
      { level: 7, overtaking: 46, defending: 56, qualifying: 51, raceStart: 66, tireManagement: 61 },
      { level: 8, overtaking: 49, defending: 59, qualifying: 54, raceStart: 69, tireManagement: 64 },
      { level: 9, overtaking: 52, defending: 62, qualifying: 57, raceStart: 72, tireManagement: 67 },
    ],
  },
  {
    id: 43,
    name: 'Liam Lawson',
    rarity: 'epic',
    series: 8,
    stats: [
      { level: 1, overtaking: 59, defending: 39, qualifying: 49, raceStart: 44, tireManagement: 54 },
      { level: 2, overtaking: 63, defending: 43, qualifying: 53, raceStart: 48, tireManagement: 58 },
      { level: 3, overtaking: 67, defending: 47, qualifying: 57, raceStart: 52, tireManagement: 62 },
      { level: 4, overtaking: 70, defending: 50, qualifying: 60, raceStart: 55, tireManagement: 65 },
      { level: 5, overtaking: 74, defending: 54, qualifying: 64, raceStart: 59, tireManagement: 69 },
      { level: 6, overtaking: 78, defending: 58, qualifying: 68, raceStart: 63, tireManagement: 73 },
      { level: 7, overtaking: 82, defending: 62, qualifying: 72, raceStart: 67, tireManagement: 77 },
      { level: 8, overtaking: 86, defending: 66, qualifying: 76, raceStart: 71, tireManagement: 81 },
    ],
  },
  {
    id: 44,
    name: 'Lewis Hamilton',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 45, defending: 35, qualifying: 40, raceStart: 30, tireManagement: 50 },
      { level: 2, overtaking: 48, defending: 38, qualifying: 43, raceStart: 33, tireManagement: 53 },
      { level: 3, overtaking: 52, defending: 42, qualifying: 47, raceStart: 37, tireManagement: 57 },
      { level: 4, overtaking: 55, defending: 45, qualifying: 50, raceStart: 40, tireManagement: 60 },
      { level: 5, overtaking: 58, defending: 48, qualifying: 53, raceStart: 43, tireManagement: 63 },
      { level: 6, overtaking: 62, defending: 52, qualifying: 57, raceStart: 47, tireManagement: 67 },
      { level: 7, overtaking: 65, defending: 55, qualifying: 60, raceStart: 50, tireManagement: 70 },
      { level: 8, overtaking: 68, defending: 58, qualifying: 63, raceStart: 53, tireManagement: 73 },
      { level: 9, overtaking: 72, defending: 62, qualifying: 67, raceStart: 57, tireManagement: 77 },
    ],
  },
  {
    id: 45,
    name: 'Charles Leclerc',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 30, defending: 40, qualifying: 45, raceStart: 50, tireManagement: 35 },
      { level: 2, overtaking: 33, defending: 43, qualifying: 48, raceStart: 53, tireManagement: 38 },
      { level: 3, overtaking: 37, defending: 47, qualifying: 52, raceStart: 57, tireManagement: 42 },
      { level: 4, overtaking: 40, defending: 50, qualifying: 55, raceStart: 60, tireManagement: 45 },
      { level: 5, overtaking: 43, defending: 53, qualifying: 58, raceStart: 63, tireManagement: 48 },
      { level: 6, overtaking: 47, defending: 57, qualifying: 62, raceStart: 67, tireManagement: 52 },
      { level: 7, overtaking: 50, defending: 60, qualifying: 65, raceStart: 70, tireManagement: 55 },
      { level: 8, overtaking: 53, defending: 63, qualifying: 68, raceStart: 73, tireManagement: 58 },
      { level: 9, overtaking: 57, defending: 67, qualifying: 72, raceStart: 77, tireManagement: 62 },
    ],
  },
  {
    id: 46,
    name: 'George Russell',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 50, defending: 30, qualifying: 35, raceStart: 40, tireManagement: 45 },
      { level: 2, overtaking: 53, defending: 33, qualifying: 38, raceStart: 43, tireManagement: 48 },
      { level: 3, overtaking: 57, defending: 37, qualifying: 42, raceStart: 47, tireManagement: 52 },
      { level: 4, overtaking: 60, defending: 40, qualifying: 45, raceStart: 50, tireManagement: 55 },
      { level: 5, overtaking: 63, defending: 43, qualifying: 48, raceStart: 53, tireManagement: 58 },
      { level: 6, overtaking: 67, defending: 47, qualifying: 52, raceStart: 57, tireManagement: 62 },
      { level: 7, overtaking: 70, defending: 50, qualifying: 55, raceStart: 60, tireManagement: 65 },
      { level: 8, overtaking: 73, defending: 53, qualifying: 58, raceStart: 63, tireManagement: 68 },
      { level: 9, overtaking: 77, defending: 57, qualifying: 62, raceStart: 67, tireManagement: 72 },
    ],
  },
  {
    id: 47,
    name: 'Oscar Piastri',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 40, defending: 50, qualifying: 30, raceStart: 45, tireManagement: 35 },
      { level: 2, overtaking: 43, defending: 53, qualifying: 33, raceStart: 48, tireManagement: 38 },
      { level: 3, overtaking: 47, defending: 57, qualifying: 37, raceStart: 52, tireManagement: 42 },
      { level: 4, overtaking: 50, defending: 60, qualifying: 40, raceStart: 55, tireManagement: 45 },
      { level: 5, overtaking: 53, defending: 63, qualifying: 43, raceStart: 58, tireManagement: 48 },
      { level: 6, overtaking: 57, defending: 67, qualifying: 47, raceStart: 62, tireManagement: 52 },
      { level: 7, overtaking: 60, defending: 70, qualifying: 50, raceStart: 65, tireManagement: 55 },
      { level: 8, overtaking: 63, defending: 73, qualifying: 53, raceStart: 68, tireManagement: 58 },
      { level: 9, overtaking: 67, defending: 77, qualifying: 57, raceStart: 72, tireManagement: 62 },
    ],
  },
  {
    id: 48,
    name: 'Max Verstappen',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 45, defending: 35, qualifying: 50, raceStart: 30, tireManagement: 40 },
      { level: 2, overtaking: 48, defending: 38, qualifying: 53, raceStart: 33, tireManagement: 43 },
      { level: 3, overtaking: 52, defending: 42, qualifying: 57, raceStart: 37, tireManagement: 47 },
      { level: 4, overtaking: 55, defending: 45, qualifying: 60, raceStart: 40, tireManagement: 50 },
      { level: 5, overtaking: 58, defending: 48, qualifying: 63, raceStart: 43, tireManagement: 53 },
      { level: 6, overtaking: 62, defending: 52, qualifying: 67, raceStart: 47, tireManagement: 57 },
      { level: 7, overtaking: 65, defending: 55, qualifying: 70, raceStart: 50, tireManagement: 60 },
      { level: 8, overtaking: 68, defending: 58, qualifying: 73, raceStart: 53, tireManagement: 63 },
      { level: 9, overtaking: 72, defending: 62, qualifying: 77, raceStart: 57, tireManagement: 67 },
    ],
  },
  {
    id: 49,
    name: 'Lando Norris',
    rarity: 'rare',
    series: 9,
    stats: [
      { level: 1, overtaking: 40, defending: 30, qualifying: 45, raceStart: 35, tireManagement: 50 },
      { level: 2, overtaking: 43, defending: 33, qualifying: 48, raceStart: 38, tireManagement: 53 },
      { level: 3, overtaking: 47, defending: 37, qualifying: 52, raceStart: 42, tireManagement: 57 },
      { level: 4, overtaking: 50, defending: 40, qualifying: 55, raceStart: 45, tireManagement: 60 },
      { level: 5, overtaking: 53, defending: 43, qualifying: 58, raceStart: 48, tireManagement: 63 },
      { level: 6, overtaking: 57, defending: 47, qualifying: 62, raceStart: 52, tireManagement: 67 },
      { level: 7, overtaking: 60, defending: 50, qualifying: 65, raceStart: 55, tireManagement: 70 },
      { level: 8, overtaking: 63, defending: 53, qualifying: 68, raceStart: 58, tireManagement: 73 },
      { level: 9, overtaking: 67, defending: 57, qualifying: 72, raceStart: 62, tireManagement: 77 },
    ],
  },
  {
    id: 50,
    name: 'Gabriel Bortoleto',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 61, defending: 45, qualifying: 53, raceStart: 57, tireManagement: 49 },
      { level: 2, overtaking: 66, defending: 49, qualifying: 57, raceStart: 61, tireManagement: 53 },
      { level: 3, overtaking: 70, defending: 52, qualifying: 61, raceStart: 65, tireManagement: 57 },
      { level: 4, overtaking: 74, defending: 56, qualifying: 65, raceStart: 69, tireManagement: 60 },
      { level: 5, overtaking: 78, defending: 60, qualifying: 69, raceStart: 73, tireManagement: 64 },
      { level: 6, overtaking: 82, defending: 63, qualifying: 72, raceStart: 77, tireManagement: 68 },
      { level: 7, overtaking: 86, defending: 67, qualifying: 76, raceStart: 81, tireManagement: 71 },
      { level: 8, overtaking: 90, defending: 70, qualifying: 80, raceStart: 85, tireManagement: 75 },
    ],
  },
  {
    id: 51,
    name: 'Lance Stroll',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 57, defending: 61, qualifying: 49, raceStart: 45, tireManagement: 53 },
      { level: 2, overtaking: 61, defending: 66, qualifying: 53, raceStart: 49, tireManagement: 57 },
      { level: 3, overtaking: 65, defending: 70, qualifying: 57, raceStart: 52, tireManagement: 61 },
      { level: 4, overtaking: 69, defending: 74, qualifying: 60, raceStart: 56, tireManagement: 65 },
      { level: 5, overtaking: 73, defending: 78, qualifying: 64, raceStart: 60, tireManagement: 69 },
      { level: 6, overtaking: 77, defending: 82, qualifying: 68, raceStart: 63, tireManagement: 72 },
      { level: 7, overtaking: 81, defending: 86, qualifying: 71, raceStart: 67, tireManagement: 76 },
      { level: 8, overtaking: 85, defending: 90, qualifying: 75, raceStart: 70, tireManagement: 80 },
    ],
  },
  {
    id: 52,
    name: 'Esteban Ocon',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 53, defending: 49, qualifying: 45, raceStart: 57, tireManagement: 61 },
      { level: 2, overtaking: 57, defending: 53, qualifying: 49, raceStart: 61, tireManagement: 66 },
      { level: 3, overtaking: 61, defending: 57, qualifying: 52, raceStart: 65, tireManagement: 70 },
      { level: 4, overtaking: 65, defending: 60, qualifying: 56, raceStart: 69, tireManagement: 74 },
      { level: 5, overtaking: 69, defending: 64, qualifying: 60, raceStart: 73, tireManagement: 78 },
      { level: 6, overtaking: 72, defending: 68, qualifying: 63, raceStart: 77, tireManagement: 82 },
      { level: 7, overtaking: 76, defending: 71, qualifying: 67, raceStart: 81, tireManagement: 86 },
      { level: 8, overtaking: 80, defending: 75, qualifying: 70, raceStart: 85, tireManagement: 90 },
    ],
  },
  {
    id: 53,
    name: 'Nico Hülkenberg',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 53, defending: 58, qualifying: 63, raceStart: 48, tireManagement: 43 },
      { level: 2, overtaking: 57, defending: 62, qualifying: 67, raceStart: 52, tireManagement: 47 },
      { level: 3, overtaking: 61, defending: 66, qualifying: 71, raceStart: 56, tireManagement: 51 },
      { level: 4, overtaking: 65, defending: 70, qualifying: 75, raceStart: 60, tireManagement: 55 },
      { level: 5, overtaking: 69, defending: 74, qualifying: 79, raceStart: 64, tireManagement: 59 },
      { level: 6, overtaking: 72, defending: 77, qualifying: 82, raceStart: 67, tireManagement: 62 },
      { level: 7, overtaking: 76, defending: 81, qualifying: 86, raceStart: 71, tireManagement: 66 },
      { level: 8, overtaking: 80, defending: 85, qualifying: 90, raceStart: 75, tireManagement: 70 },
    ],
  },
  {
    id: 54,
    name: 'Alex Albon',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 43, defending: 63, qualifying: 58, raceStart: 48, tireManagement: 53 },
      { level: 2, overtaking: 48, defending: 67, qualifying: 62, raceStart: 54, tireManagement: 56 },
      { level: 3, overtaking: 52, defending: 71, qualifying: 65, raceStart: 59, tireManagement: 58 },
      { level: 4, overtaking: 57, defending: 75, qualifying: 68, raceStart: 64, tireManagement: 61 },
      { level: 5, overtaking: 62, defending: 79, qualifying: 71, raceStart: 69, tireManagement: 63 },
      { level: 6, overtaking: 66, defending: 82, qualifying: 74, raceStart: 75, tireManagement: 65 },
      { level: 7, overtaking: 71, defending: 86, qualifying: 77, raceStart: 80, tireManagement: 68 },
      { level: 8, overtaking: 75, defending: 90, qualifying: 80, raceStart: 85, tireManagement: 70 },
    ],
  },
  {
    id: 55,
    name: 'Sergio Perez',
    rarity: 'epic',
    series: 10,
    stats: [
      { level: 1, overtaking: 43, defending: 53, qualifying: 48, raceStart: 63, tireManagement: 58 },
      { level: 2, overtaking: 47, defending: 57, qualifying: 52, raceStart: 67, tireManagement: 62 },
      { level: 3, overtaking: 51, defending: 61, qualifying: 56, raceStart: 71, tireManagement: 66 },
      { level: 4, overtaking: 55, defending: 65, qualifying: 60, raceStart: 75, tireManagement: 70 },
      { level: 5, overtaking: 59, defending: 69, qualifying: 64, raceStart: 79, tireManagement: 74 },
      { level: 6, overtaking: 62, defending: 72, qualifying: 67, raceStart: 82, tireManagement: 77 },
      { level: 7, overtaking: 66, defending: 76, qualifying: 71, raceStart: 86, tireManagement: 81 },
      { level: 8, overtaking: 70, defending: 80, qualifying: 75, raceStart: 90, tireManagement: 85 },
    ],
  },
  {
    id: 56,
    name: 'Oliver Bearman',
    rarity: 'epic',
    series: 11,
    stats: [
      { level: 1, overtaking: 53, defending: 58, qualifying: 63, raceStart: 68, tireManagement: 48 },
      { level: 2, overtaking: 57, defending: 62, qualifying: 67, raceStart: 72, tireManagement: 52 },
      { level: 3, overtaking: 60, defending: 65, qualifying: 70, raceStart: 75, tireManagement: 55 },
      { level: 4, overtaking: 64, defending: 69, qualifying: 74, raceStart: 79, tireManagement: 59 },
      { level: 5, overtaking: 68, defending: 73, qualifying: 78, raceStart: 83, tireManagement: 63 },
      { level: 6, overtaking: 72, defending: 77, qualifying: 82, raceStart: 87, tireManagement: 67 },
      { level: 7, overtaking: 76, defending: 81, qualifying: 86, raceStart: 91, tireManagement: 71 },
      { level: 8, overtaking: 80, defending: 85, qualifying: 90, raceStart: 95, tireManagement: 75 },
    ],
  },
  {
    id: 57,
    name: 'Isack Hadjar',
    rarity: 'epic',
    series: 11,
    stats: [
      { level: 1, overtaking: 63, defending: 68, qualifying: 48, raceStart: 58, tireManagement: 53 },
      { level: 2, overtaking: 67, defending: 72, qualifying: 52, raceStart: 62, tireManagement: 57 },
      { level: 3, overtaking: 70, defending: 75, qualifying: 55, raceStart: 65, tireManagement: 60 },
      { level: 4, overtaking: 74, defending: 79, qualifying: 59, raceStart: 69, tireManagement: 64 },
      { level: 5, overtaking: 78, defending: 83, qualifying: 63, raceStart: 73, tireManagement: 68 },
      { level: 6, overtaking: 82, defending: 87, qualifying: 67, raceStart: 77, tireManagement: 72 },
      { level: 7, overtaking: 86, defending: 91, qualifying: 71, raceStart: 81, tireManagement: 76 },
      { level: 8, overtaking: 90, defending: 95, qualifying: 75, raceStart: 85, tireManagement: 80 },
    ],
  },
  {
    id: 58,
    name: 'Fernando Alonso',
    rarity: 'epic',
    series: 11,
    stats: [
      { level: 1, overtaking: 68, defending: 53, qualifying: 48, raceStart: 63, tireManagement: 58 },
      { level: 2, overtaking: 72, defending: 57, qualifying: 52, raceStart: 67, tireManagement: 62 },
      { level: 3, overtaking: 75, defending: 60, qualifying: 55, raceStart: 70, tireManagement: 65 },
      { level: 4, overtaking: 79, defending: 64, qualifying: 59, raceStart: 74, tireManagement: 69 },
      { level: 5, overtaking: 83, defending: 68, qualifying: 63, raceStart: 78, tireManagement: 73 },
      { level: 6, overtaking: 87, defending: 72, qualifying: 67, raceStart: 82, tireManagement: 77 },
      { level: 7, overtaking: 91, defending: 76, qualifying: 71, raceStart: 86, tireManagement: 81 },
      { level: 8, overtaking: 95, defending: 80, qualifying: 75, raceStart: 90, tireManagement: 85 },
    ],
  },
  {
    id: 59,
    name: 'Carlos Sainz',
    rarity: 'epic',
    series: 11,
    stats: [
      { level: 1, overtaking: 53, defending: 63, qualifying: 58, raceStart: 48, tireManagement: 68 },
      { level: 2, overtaking: 57, defending: 67, qualifying: 62, raceStart: 52, tireManagement: 72 },
      { level: 3, overtaking: 60, defending: 70, qualifying: 65, raceStart: 55, tireManagement: 75 },
      { level: 4, overtaking: 64, defending: 74, qualifying: 69, raceStart: 59, tireManagement: 79 },
      { level: 5, overtaking: 68, defending: 78, qualifying: 73, raceStart: 63, tireManagement: 83 },
      { level: 6, overtaking: 72, defending: 82, qualifying: 77, raceStart: 67, tireManagement: 87 },
      { level: 7, overtaking: 76, defending: 86, qualifying: 81, raceStart: 71, tireManagement: 91 },
      { level: 8, overtaking: 80, defending: 90, qualifying: 85, raceStart: 75, tireManagement: 95 },
    ],
  },
  {
    id: 60,
    name: 'Andrea Kimi Antonelli',
    rarity: 'epic',
    series: 11,
    stats: [
      { level: 1, overtaking: 58, defending: 48, qualifying: 68, raceStart: 63, tireManagement: 53 },
      { level: 2, overtaking: 62, defending: 52, qualifying: 72, raceStart: 67, tireManagement: 57 },
      { level: 3, overtaking: 65, defending: 55, qualifying: 75, raceStart: 70, tireManagement: 60 },
      { level: 4, overtaking: 69, defending: 59, qualifying: 79, raceStart: 74, tireManagement: 64 },
      { level: 5, overtaking: 73, defending: 63, qualifying: 83, raceStart: 78, tireManagement: 68 },
      { level: 6, overtaking: 77, defending: 67, qualifying: 87, raceStart: 82, tireManagement: 72 },
      { level: 7, overtaking: 81, defending: 71, qualifying: 91, raceStart: 86, tireManagement: 76 },
      { level: 8, overtaking: 85, defending: 75, qualifying: 95, raceStart: 90, tireManagement: 80 },
    ],
  },
  {
    id: 61,
    name: 'Lewis Hamilton',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 67, defending: 57, qualifying: 62, raceStart: 52, tireManagement: 72 },
      { level: 2, overtaking: 71, defending: 61, qualifying: 66, raceStart: 56, tireManagement: 76 },
      { level: 3, overtaking: 75, defending: 65, qualifying: 70, raceStart: 60, tireManagement: 80 },
      { level: 4, overtaking: 79, defending: 69, qualifying: 74, raceStart: 64, tireManagement: 84 },
      { level: 5, overtaking: 83, defending: 73, qualifying: 78, raceStart: 68, tireManagement: 88 },
      { level: 6, overtaking: 86, defending: 76, qualifying: 81, raceStart: 71, tireManagement: 91 },
      { level: 7, overtaking: 90, defending: 80, qualifying: 85, raceStart: 75, tireManagement: 95 },
      { level: 8, overtaking: 94, defending: 84, qualifying: 89, raceStart: 79, tireManagement: 99 },
    ],
  },
  {
    id: 62,
    name: 'Charles Leclerc',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 52, defending: 62, qualifying: 67, raceStart: 72, tireManagement: 57 },
      { level: 2, overtaking: 56, defending: 66, qualifying: 71, raceStart: 76, tireManagement: 61 },
      { level: 3, overtaking: 60, defending: 70, qualifying: 75, raceStart: 80, tireManagement: 65 },
      { level: 4, overtaking: 64, defending: 74, qualifying: 79, raceStart: 84, tireManagement: 69 },
      { level: 5, overtaking: 68, defending: 78, qualifying: 83, raceStart: 88, tireManagement: 73 },
      { level: 6, overtaking: 71, defending: 81, qualifying: 86, raceStart: 91, tireManagement: 76 },
      { level: 7, overtaking: 75, defending: 85, qualifying: 90, raceStart: 95, tireManagement: 80 },
      { level: 8, overtaking: 79, defending: 89, qualifying: 94, raceStart: 99, tireManagement: 84 },
    ],
  },
  {
    id: 63,
    name: 'George Russell',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 72, defending: 52, qualifying: 57, raceStart: 62, tireManagement: 67 },
      { level: 2, overtaking: 76, defending: 56, qualifying: 61, raceStart: 66, tireManagement: 71 },
      { level: 3, overtaking: 80, defending: 60, qualifying: 65, raceStart: 70, tireManagement: 75 },
      { level: 4, overtaking: 84, defending: 64, qualifying: 69, raceStart: 74, tireManagement: 79 },
      { level: 5, overtaking: 88, defending: 68, qualifying: 73, raceStart: 78, tireManagement: 83 },
      { level: 6, overtaking: 91, defending: 71, qualifying: 76, raceStart: 81, tireManagement: 86 },
      { level: 7, overtaking: 95, defending: 75, qualifying: 80, raceStart: 85, tireManagement: 90 },
      { level: 8, overtaking: 99, defending: 79, qualifying: 84, raceStart: 89, tireManagement: 94 },
    ],
  },
  {
    id: 64,
    name: 'Oscar Piastri',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 62, defending: 72, qualifying: 52, raceStart: 67, tireManagement: 57 },
      { level: 2, overtaking: 66, defending: 76, qualifying: 56, raceStart: 71, tireManagement: 61 },
      { level: 3, overtaking: 70, defending: 80, qualifying: 60, raceStart: 75, tireManagement: 65 },
      { level: 4, overtaking: 74, defending: 84, qualifying: 64, raceStart: 79, tireManagement: 69 },
      { level: 5, overtaking: 78, defending: 88, qualifying: 68, raceStart: 83, tireManagement: 73 },
      { level: 6, overtaking: 81, defending: 91, qualifying: 71, raceStart: 86, tireManagement: 76 },
      { level: 7, overtaking: 85, defending: 95, qualifying: 75, raceStart: 90, tireManagement: 80 },
      { level: 8, overtaking: 89, defending: 99, qualifying: 79, raceStart: 94, tireManagement: 84 },
    ],
  },
  {
    id: 65,
    name: 'Max Verstappen',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 67, defending: 57, qualifying: 72, raceStart: 52, tireManagement: 62 },
      { level: 2, overtaking: 71, defending: 61, qualifying: 76, raceStart: 56, tireManagement: 66 },
      { level: 3, overtaking: 75, defending: 65, qualifying: 80, raceStart: 60, tireManagement: 70 },
      { level: 4, overtaking: 79, defending: 69, qualifying: 84, raceStart: 64, tireManagement: 74 },
      { level: 5, overtaking: 83, defending: 73, qualifying: 88, raceStart: 68, tireManagement: 78 },
      { level: 6, overtaking: 86, defending: 76, qualifying: 91, raceStart: 71, tireManagement: 81 },
      { level: 7, overtaking: 90, defending: 80, qualifying: 95, raceStart: 75, tireManagement: 85 },
      { level: 8, overtaking: 94, defending: 84, qualifying: 99, raceStart: 79, tireManagement: 89 },
    ],
  },
  {
    id: 66,
    name: 'Lando Norris',
    rarity: 'epic',
    series: 12,
    stats: [
      { level: 1, overtaking: 62, defending: 52, qualifying: 67, raceStart: 57, tireManagement: 72 },
      { level: 2, overtaking: 66, defending: 56, qualifying: 71, raceStart: 61, tireManagement: 76 },
      { level: 3, overtaking: 70, defending: 60, qualifying: 75, raceStart: 65, tireManagement: 80 },
      { level: 4, overtaking: 74, defending: 64, qualifying: 79, raceStart: 69, tireManagement: 84 },
      { level: 5, overtaking: 78, defending: 68, qualifying: 83, raceStart: 73, tireManagement: 88 },
      { level: 6, overtaking: 81, defending: 71, qualifying: 86, raceStart: 76, tireManagement: 91 },
      { level: 7, overtaking: 85, defending: 75, qualifying: 90, raceStart: 80, tireManagement: 95 },
      { level: 8, overtaking: 89, defending: 79, qualifying: 94, raceStart: 84, tireManagement: 99 },
    ],
  },
      {
    id: 67,
    name: 'Giancarlo Fisichella',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 18, defending: 14, qualifying: 22, raceStart: 30, tireManagement: 26 },
      { level: 2, overtaking: 23, defending: 19, qualifying: 27, raceStart: 35, tireManagement: 31 },
      { level: 3, overtaking: 27, defending: 23, qualifying: 31, raceStart: 39, tireManagement: 35 },
      { level: 4, overtaking: 32, defending: 28, qualifying: 36, raceStart: 44, tireManagement: 40 },
      { level: 5, overtaking: 36, defending: 32, qualifying: 40, raceStart: 48, tireManagement: 44 },
      { level: 6, overtaking: 41, defending: 37, qualifying: 45, raceStart: 53, tireManagement: 49 },
      { level: 7, overtaking: 45, defending: 41, qualifying: 49, raceStart: 57, tireManagement: 53 },
    ],
  },
  {
    id: 68,
    name: 'Bruce McLaren',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 22, defending: 26, qualifying: 30, raceStart: 14, tireManagement: 18 },
      { level: 2, overtaking: 27, defending: 31, qualifying: 35, raceStart: 19, tireManagement: 23 },
      { level: 3, overtaking: 31, defending: 35, qualifying: 39, raceStart: 23, tireManagement: 27 },
      { level: 4, overtaking: 36, defending: 40, qualifying: 44, raceStart: 28, tireManagement: 32 },
      { level: 5, overtaking: 40, defending: 44, qualifying: 48, raceStart: 32, tireManagement: 36 },
      { level: 6, overtaking: 45, defending: 49, qualifying: 53, raceStart: 37, tireManagement: 41 },
      { level: 7, overtaking: 49, defending: 53, qualifying: 57, raceStart: 41, tireManagement: 45 },
    ],
  },
  {
    id: 69,
    name: 'Gilles Villeneuve',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 26, defending: 22, qualifying: 14, raceStart: 18, tireManagement: 30 },
      { level: 2, overtaking: 31, defending: 27, qualifying: 19, raceStart: 23, tireManagement: 35 },
      { level: 3, overtaking: 35, defending: 31, qualifying: 23, raceStart: 27, tireManagement: 39 },
      { level: 4, overtaking: 40, defending: 36, qualifying: 28, raceStart: 32, tireManagement: 44 },
      { level: 5, overtaking: 44, defending: 40, qualifying: 32, raceStart: 36, tireManagement: 48 },
      { level: 6, overtaking: 49, defending: 45, qualifying: 37, raceStart: 41, tireManagement: 53 },
      { level: 7, overtaking: 53, defending: 49, qualifying: 41, raceStart: 45, tireManagement: 57 },
    ],
  },
  {
    id: 70,
    name: 'Mark Webber',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 28, defending: 52, qualifying: 34, raceStart: 46, tireManagement: 40 },
      { level: 2, overtaking: 33, defending: 57, qualifying: 39, raceStart: 51, tireManagement: 45 },
      { level: 3, overtaking: 37, defending: 61, qualifying: 43, raceStart: 55, tireManagement: 49 },
      { level: 4, overtaking: 41, defending: 65, qualifying: 47, raceStart: 59, tireManagement: 53 },
      { level: 5, overtaking: 46, defending: 70, qualifying: 52, raceStart: 64, tireManagement: 58 },
      { level: 6, overtaking: 50, defending: 74, qualifying: 56, raceStart: 68, tireManagement: 62 },
      { level: 7, overtaking: 55, defending: 79, qualifying: 61, raceStart: 73, tireManagement: 67 },
    ],
  },
  {
    id: 71,
    name: 'Gerhard Berger',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 52, defending: 34, qualifying: 28, raceStart: 40, tireManagement: 46 },
      { level: 2, overtaking: 57, defending: 39, qualifying: 33, raceStart: 45, tireManagement: 51 },
      { level: 3, overtaking: 61, defending: 43, qualifying: 37, raceStart: 49, tireManagement: 55 },
      { level: 4, overtaking: 65, defending: 47, qualifying: 41, raceStart: 53, tireManagement: 59 },
      { level: 5, overtaking: 70, defending: 52, qualifying: 46, raceStart: 58, tireManagement: 64 },
      { level: 6, overtaking: 74, defending: 56, qualifying: 50, raceStart: 62, tireManagement: 68 },
      { level: 7, overtaking: 79, defending: 61, qualifying: 55, raceStart: 67, tireManagement: 73 },
    ],
  },
  {
    id: 72,
    name: 'Felipe Massa',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 28, defending: 46, qualifying: 40, raceStart: 52, tireManagement: 34 },
      { level: 2, overtaking: 33, defending: 51, qualifying: 45, raceStart: 57, tireManagement: 39 },
      { level: 3, overtaking: 37, defending: 55, qualifying: 49, raceStart: 61, tireManagement: 43 },
      { level: 4, overtaking: 41, defending: 59, qualifying: 53, raceStart: 65, tireManagement: 47 },
      { level: 5, overtaking: 46, defending: 64, qualifying: 58, raceStart: 70, tireManagement: 52 },
      { level: 6, overtaking: 50, defending: 68, qualifying: 62, raceStart: 74, tireManagement: 56 },
      { level: 7, overtaking: 55, defending: 73, qualifying: 67, raceStart: 79, tireManagement: 61 },
    ],
  },
  {
    id: 73,
    name: 'David Coulthard',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 34, defending: 40, qualifying: 46, raceStart: 28, tireManagement: 52 },
      { level: 2, overtaking: 39, defending: 45, qualifying: 51, raceStart: 33, tireManagement: 57 },
      { level: 3, overtaking: 43, defending: 49, qualifying: 55, raceStart: 37, tireManagement: 61 },
      { level: 4, overtaking: 47, defending: 53, qualifying: 59, raceStart: 41, tireManagement: 65 },
      { level: 5, overtaking: 52, defending: 58, qualifying: 64, raceStart: 46, tireManagement: 70 },
      { level: 6, overtaking: 56, defending: 62, qualifying: 68, raceStart: 50, tireManagement: 74 },
      { level: 7, overtaking: 61, defending: 67, qualifying: 73, raceStart: 55, tireManagement: 79 },
    ],
  },
  {
    id: 74,
    name: 'Jochen Rindt',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 40, defending: 28, qualifying: 52, raceStart: 34, tireManagement: 46 },
      { level: 2, overtaking: 45, defending: 33, qualifying: 57, raceStart: 39, tireManagement: 51 },
      { level: 3, overtaking: 49, defending: 37, qualifying: 61, raceStart: 43, tireManagement: 55 },
      { level: 4, overtaking: 53, defending: 41, qualifying: 65, raceStart: 47, tireManagement: 59 },
      { level: 5, overtaking: 58, defending: 46, qualifying: 70, raceStart: 52, tireManagement: 64 },
      { level: 6, overtaking: 62, defending: 50, qualifying: 74, raceStart: 56, tireManagement: 68 },
      { level: 7, overtaking: 67, defending: 55, qualifying: 79, raceStart: 61, tireManagement: 73 },
    ],
  },
  {
    id: 75,
    name: 'James Hunt',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 41, defending: 59, qualifying: 65, raceStart: 47, tireManagement: 53 },
      { level: 2, overtaking: 46, defending: 64, qualifying: 70, raceStart: 52, tireManagement: 58 },
      { level: 3, overtaking: 50, defending: 68, qualifying: 74, raceStart: 56, tireManagement: 62 },
      { level: 4, overtaking: 55, defending: 73, qualifying: 79, raceStart: 61, tireManagement: 67 },
      { level: 5, overtaking: 59, defending: 77, qualifying: 83, raceStart: 65, tireManagement: 71 },
      { level: 6, overtaking: 64, defending: 82, qualifying: 88, raceStart: 70, tireManagement: 76 },
      { level: 7, overtaking: 68, defending: 86, qualifying: 92, raceStart: 74, tireManagement: 80 },
    ],
  },
  {
    id: 76,
    name: 'Jacques Villeneuve',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 65, defending: 47, qualifying: 53, raceStart: 59, tireManagement: 41 },
      { level: 2, overtaking: 70, defending: 52, qualifying: 58, raceStart: 64, tireManagement: 46 },
      { level: 3, overtaking: 74, defending: 56, qualifying: 62, raceStart: 68, tireManagement: 50 },
      { level: 4, overtaking: 79, defending: 61, qualifying: 67, raceStart: 73, tireManagement: 55 },
      { level: 5, overtaking: 83, defending: 65, qualifying: 71, raceStart: 77, tireManagement: 59 },
      { level: 6, overtaking: 88, defending: 70, qualifying: 76, raceStart: 82, tireManagement: 64 },
      { level: 7, overtaking: 92, defending: 74, qualifying: 80, raceStart: 86, tireManagement: 68 },
    ],
  },
  {
    id: 77,
    name: 'Mario Andretti',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 59, defending: 53, qualifying: 41, raceStart: 65, tireManagement: 47 },
      { level: 2, overtaking: 64, defending: 58, qualifying: 46, raceStart: 70, tireManagement: 52 },
      { level: 3, overtaking: 68, defending: 62, qualifying: 50, raceStart: 74, tireManagement: 56 },
      { level: 4, overtaking: 73, defending: 67, qualifying: 55, raceStart: 79, tireManagement: 61 },
      { level: 5, overtaking: 77, defending: 71, qualifying: 59, raceStart: 83, tireManagement: 65 },
      { level: 6, overtaking: 82, defending: 76, qualifying: 64, raceStart: 88, tireManagement: 70 },
      { level: 7, overtaking: 86, defending: 80, qualifying: 68, raceStart: 92, tireManagement: 74 },
    ],
  },
  {
    id: 78,
    name: 'Jenson Button',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 53, defending: 59, qualifying: 47, raceStart: 41, tireManagement: 65 },
      { level: 2, overtaking: 58, defending: 64, qualifying: 52, raceStart: 46, tireManagement: 70 },
      { level: 3, overtaking: 62, defending: 68, qualifying: 56, raceStart: 50, tireManagement: 74 },
      { level: 4, overtaking: 67, defending: 73, qualifying: 61, raceStart: 55, tireManagement: 79 },
      { level: 5, overtaking: 71, defending: 77, qualifying: 65, raceStart: 59, tireManagement: 83 },
      { level: 6, overtaking: 76, defending: 82, qualifying: 70, raceStart: 64, tireManagement: 88 },
      { level: 7, overtaking: 80, defending: 86, qualifying: 74, raceStart: 68, tireManagement: 92 },
    ],
  },
  {
    id: 79,
    name: 'Damon Hill',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 41, defending: 65, qualifying: 53, raceStart: 59, tireManagement: 47 },
      { level: 2, overtaking: 46, defending: 70, qualifying: 58, raceStart: 64, tireManagement: 52 },
      { level: 3, overtaking: 50, defending: 74, qualifying: 62, raceStart: 68, tireManagement: 56 },
      { level: 4, overtaking: 55, defending: 79, qualifying: 67, raceStart: 73, tireManagement: 61 },
      { level: 5, overtaking: 59, defending: 83, qualifying: 71, raceStart: 77, tireManagement: 65 },
      { level: 6, overtaking: 64, defending: 88, qualifying: 76, raceStart: 82, tireManagement: 70 },
      { level: 7, overtaking: 68, defending: 92, qualifying: 80, raceStart: 86, tireManagement: 74 },
    ],
  },
  {
    id: 80,
    name: 'Nigel Mansell',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 52, defending: 64, qualifying: 70, raceStart: 58, tireManagement: 46 },
      { level: 2, overtaking: 56, defending: 68, qualifying: 74, raceStart: 62, tireManagement: 50 },
      { level: 3, overtaking: 61, defending: 73, qualifying: 79, raceStart: 67, tireManagement: 55 },
      { level: 4, overtaking: 65, defending: 77, qualifying: 83, raceStart: 71, tireManagement: 59 },
      { level: 5, overtaking: 70, defending: 82, qualifying: 88, raceStart: 76, tireManagement: 64 },
      { level: 6, overtaking: 74, defending: 86, qualifying: 92, raceStart: 80, tireManagement: 68 },
      { level: 7, overtaking: 79, defending: 91, qualifying: 97, raceStart: 85, tireManagement: 73 },
    ],
  },
  {
    id: 81,
    name: 'Graham Hill',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 61, defending: 73, qualifying: 67, raceStart: 64, tireManagement: 70 },
      { level: 2, overtaking: 65, defending: 77, qualifying: 71, raceStart: 68, tireManagement: 74 },
      { level: 3, overtaking: 70, defending: 82, qualifying: 76, raceStart: 73, tireManagement: 79 },
      { level: 4, overtaking: 74, defending: 86, qualifying: 80, raceStart: 77, tireManagement: 83 },
      { level: 5, overtaking: 79, defending: 91, qualifying: 85, raceStart: 82, tireManagement: 88 },
      { level: 6, overtaking: 83, defending: 95, qualifying: 89, raceStart: 86, tireManagement: 92 },
      { level: 7, overtaking: 87, defending: 99, qualifying: 93, raceStart: 90, tireManagement: 96 },
    ],
  },
  {
    id: 82,
    name: 'Emerson Fittipaldi',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 73, defending: 67, qualifying: 70, raceStart: 61, tireManagement: 64 },
      { level: 2, overtaking: 77, defending: 71, qualifying: 74, raceStart: 65, tireManagement: 68 },
      { level: 3, overtaking: 82, defending: 76, qualifying: 79, raceStart: 70, tireManagement: 73 },
      { level: 4, overtaking: 86, defending: 80, qualifying: 83, raceStart: 74, tireManagement: 77 },
      { level: 5, overtaking: 91, defending: 85, qualifying: 88, raceStart: 79, tireManagement: 82 },
      { level: 6, overtaking: 95, defending: 89, qualifying: 92, raceStart: 83, tireManagement: 86 },
      { level: 7, overtaking: 99, defending: 93, qualifying: 96, raceStart: 87, tireManagement: 90 },
    ],
  },
  {
    id: 83,
    name: 'Niki Lauda',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 67, defending: 61, qualifying: 70, raceStart: 73, tireManagement: 64 },
      { level: 2, overtaking: 71, defending: 65, qualifying: 74, raceStart: 77, tireManagement: 68 },
      { level: 3, overtaking: 76, defending: 70, qualifying: 79, raceStart: 82, tireManagement: 73 },
      { level: 4, overtaking: 80, defending: 74, qualifying: 83, raceStart: 86, tireManagement: 77 },
      { level: 5, overtaking: 85, defending: 79, qualifying: 88, raceStart: 91, tireManagement: 82 },
      { level: 6, overtaking: 89, defending: 83, qualifying: 92, raceStart: 95, tireManagement: 86 },
      { level: 7, overtaking: 93, defending: 87, qualifying: 96, raceStart: 99, tireManagement: 90 },
    ],
  },
  {
    id: 84,
    name: 'Jack Brabham',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 61, defending: 64, qualifying: 73, raceStart: 67, tireManagement: 70 },
      { level: 2, overtaking: 65, defending: 68, qualifying: 77, raceStart: 71, tireManagement: 74 },
      { level: 3, overtaking: 70, defending: 73, qualifying: 82, raceStart: 76, tireManagement: 79 },
      { level: 4, overtaking: 74, defending: 77, qualifying: 86, raceStart: 80, tireManagement: 83 },
      { level: 5, overtaking: 79, defending: 82, qualifying: 91, raceStart: 85, tireManagement: 88 },
      { level: 6, overtaking: 83, defending: 86, qualifying: 95, raceStart: 89, tireManagement: 92 },
      { level: 7, overtaking: 87, defending: 90, qualifying: 99, raceStart: 93, tireManagement: 96 },
    ],
  },
  {
    id: 85,
    name: 'Juan Manuel Fangio',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 71, defending: 62, qualifying: 74, raceStart: 65, tireManagement: 68 },
      { level: 2, overtaking: 75, defending: 66, qualifying: 78, raceStart: 69, tireManagement: 72 },
      { level: 3, overtaking: 80, defending: 71, qualifying: 83, raceStart: 74, tireManagement: 77 },
      { level: 4, overtaking: 84, defending: 75, qualifying: 87, raceStart: 78, tireManagement: 81 },
      { level: 5, overtaking: 88, defending: 79, qualifying: 91, raceStart: 82, tireManagement: 85 },
      { level: 6, overtaking: 93, defending: 84, qualifying: 96, raceStart: 87, tireManagement: 90 },
      { level: 7, overtaking: 97, defending: 88, qualifying: 100, raceStart: 91, tireManagement: 94 },
    ],
  },
  {
    id: 86,
    name: 'Alain Prost',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 66, defending: 69, qualifying: 63, raceStart: 72, tireManagement: 75 },
      { level: 2, overtaking: 70, defending: 73, qualifying: 67, raceStart: 76, tireManagement: 79 },
      { level: 3, overtaking: 74, defending: 77, qualifying: 71, raceStart: 80, tireManagement: 83 },
      { level: 4, overtaking: 79, defending: 82, qualifying: 76, raceStart: 85, tireManagement: 88 },
      { level: 5, overtaking: 83, defending: 86, qualifying: 80, raceStart: 89, tireManagement: 92 },
      { level: 6, overtaking: 88, defending: 91, qualifying: 85, raceStart: 94, tireManagement: 97 },
      { level: 7, overtaking: 92, defending: 95, qualifying: 89, raceStart: 98, tireManagement: 101 },
    ],
  },
  {
    id: 87,
    name: 'Michael Schumacher',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 75, defending: 72, qualifying: 66, raceStart: 63, tireManagement: 69 },
      { level: 2, overtaking: 80, defending: 77, qualifying: 71, raceStart: 68, tireManagement: 74 },
      { level: 3, overtaking: 84, defending: 81, qualifying: 75, raceStart: 72, tireManagement: 78 },
      { level: 4, overtaking: 89, defending: 86, qualifying: 80, raceStart: 77, tireManagement: 83 },
      { level: 5, overtaking: 93, defending: 90, qualifying: 84, raceStart: 81, tireManagement: 87 },
      { level: 6, overtaking: 98, defending: 95, qualifying: 89, raceStart: 86, tireManagement: 92 },
      { level: 7, overtaking: 102, defending: 99, qualifying: 93, raceStart: 90, tireManagement: 96 },
    ],
  },
  {
    id: 88,
    name: 'Ayrton Senna',
    rarity: 'legendary',
    series: 12,
    stats: [
      { level: 1, overtaking: 71, defending: 71, qualifying: 71, raceStart: 71, tireManagement: 71 },
      { level: 2, overtaking: 76, defending: 76, qualifying: 76, raceStart: 76, tireManagement: 76 },
      { level: 3, overtaking: 80, defending: 80, qualifying: 80, raceStart: 80, tireManagement: 80 },
      { level: 4, overtaking: 85, defending: 85, qualifying: 85, raceStart: 85, tireManagement: 85 },
      { level: 5, overtaking: 90, defending: 90, qualifying: 90, raceStart: 90, tireManagement: 90 },
      { level: 6, overtaking: 94, defending: 94, qualifying: 94, raceStart: 94, tireManagement: 94 },
      { level: 7, overtaking: 99, defending: 99, qualifying: 99, raceStart: 99, tireManagement: 99 },
    ],
  },
] as Driver[];

const createDrivers = () => {
  const driversToSave = prepareDriversData(DRIVERS);

  console.log('Creating drivers file >>');
  createFile('src/features/drivers/constants/drivers.json', driversToSave);
};

export default createDrivers;
